name = "zengate-global/oracle-consumer"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'zengate-global/oracle-consumer'"

[repository]
user = "zengate-global"
project = "oracle-consumer"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "2.1.0"
source = "github"

[config]
